import { Amplify } from 'aws-amplify'

// This will be generated by Amplify during build
// For local development, you can use sandbox mode
const amplifyConfig = {
  API: {
    GraphQL: {
      endpoint: import.meta.env.VITE_AMPLIFY_GRAPHQL_ENDPOINT || '',
      region: import.meta.env.VITE_AWS_REGION || 'us-east-1',
      defaultAuthMode: 'apiKey' as const,
      apiKey: import.meta.env.VITE_AMPLIFY_API_KEY || '',
    }
  }
}

// Only configure if we have the endpoint (in production)
if (amplifyConfig.API.GraphQL.endpoint) {
  Amplify.configure(amplifyConfig)
}

export { amplifyConfig }
