import { Amplify } from 'aws-amplify'

// Check if amplify outputs exist and configure
// This file is generated by Amplify during deployment
let isConfigured = false

try {
  // @ts-ignore - dynamic import may fail in dev
  const outputs = import.meta.glob('../amplify_outputs.json', { eager: true })
  const outputsPath = '../amplify_outputs.json'
  
  if (outputs[outputsPath]) {
    // @ts-ignore
    Amplify.configure(outputs[outputsPath].default || outputs[outputsPath])
    isConfigured = true
  }
} catch (error) {
  // amplify_outputs.json doesn't exist, running in development mode
  console.log('Running in development mode without Amplify backend')
}

export { isConfigured }
